"""Agent interface and stub implementations.

Every agent is a stateless callable: it receives the state header, a way to
fetch detail on demand (the minimum-context rule of §6), and a workspace path,
and it returns an :class:`AgentResult`. Real agents will issue model calls; the
stubs here do deterministic local work so the gate model can be proven
end-to-end without API keys or network (§25.2, step 3).
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Protocol

from .state import StateHeader


@dataclass
class AgentResult:
    """What an agent returns to the orchestrator.

    Attributes:
        ok: Whether the agent completed its work successfully.
        tokens: Tokens consumed (recorded by the cost governor).
        detail_patch: Keys to merge into the state detail blob.
        summary: One-line human-readable summary for the decision log.
        artifacts: Paths of files the agent wrote, for traceability.
    """

    ok: bool = True
    tokens: int = 0
    detail_patch: dict[str, Any] = field(default_factory=dict)
    summary: str = ""
    artifacts: list[str] = field(default_factory=list)


class Agent(Protocol):
    """Structural type for an agent callable."""

    def __call__(
        self, header: StateHeader, fetch_detail: Callable[[], dict[str, Any]], workspace: Path
    ) -> AgentResult: ...


class StubPM:
    """Deterministic stand-in for the PM agent.

    Writes a minimal PRD artifact so the DEFINE -> PRD_APPROVAL gate has
    something concrete to approve.
    """

    def __call__(
        self, header: StateHeader, fetch_detail: Callable[[], dict[str, Any]], workspace: Path
    ) -> AgentResult:
        prd_dir = workspace / "wiki" / "projects" / header.project_id
        prd_dir.mkdir(parents=True, exist_ok=True)
        prd_path = prd_dir / "PRD.md"
        prd_path.write_text(
            f"# PRD — {header.project_id}\n\n"
            f"Tier: {header.tier}  Mode: {header.mode}  Size: {header.complexity}\n\n"
            "## Problem statement\nStub PRD generated by the control-plane demo.\n\n"
            "## Acceptance criteria\n1. The gate model halts and resumes correctly.\n"
        )
        return AgentResult(
            ok=True,
            tokens=1200,
            detail_patch={"links": {"prd": str(prd_path.relative_to(workspace))}},
            summary="PRD drafted (stub)",
            artifacts=[str(prd_path.relative_to(workspace))],
        )


def stub_agent(name: str, tokens: int = 800) -> Agent:
    """Build a generic stub agent that succeeds and records ``tokens``."""

    def _run(
        header: StateHeader, fetch_detail: Callable[[], dict[str, Any]], workspace: Path
    ) -> AgentResult:
        return AgentResult(ok=True, tokens=tokens, summary=f"{name} completed (stub)")

    return _run


def default_registry() -> dict[str, Agent]:
    """Return a registry mapping every owner role to a stub implementation."""
    return {
        "PM": StubPM(),
        "Architect": stub_agent("Architect", 1500),
        "ReviewPanel": stub_agent("ReviewPanel", 3000),
        "Dev": stub_agent("Dev", 4000),
        "QA": stub_agent("QA", 2000),
        "CICD": stub_agent("CICD", 600),
        "Monitor": stub_agent("Monitor", 500),
    }


def live_registry() -> dict[str, Agent]:
    """Return a registry with the real PM agent wired in; all others remain stubs.

    Use this for interactive demos and live runs. Tests should use
    ``default_registry()`` with ``call_claude`` mocked to avoid network calls.
    """
    from .agents_pm import PMAgent  # local import keeps the stub path dependency-free

    registry = default_registry()
    registry["PM"] = PMAgent()
    return registry
