"""Agent interface and stub implementations.

Every agent is a stateless callable: it receives the state header, a way to
fetch detail on demand (the minimum-context rule of §6), and a workspace path,
and it returns an :class:`AgentResult`. Real agents will issue model calls; the
stubs here do deterministic local work so the gate model can be proven
end-to-end without API keys or network (§25.2, step 3).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Callable

from .agents_architect import ArchitectAgent
from .agents_pm import PMAgent
from .protocol import Agent, AgentResult
from .state import StateHeader


class StubPM:
    """Deterministic stand-in for the PM agent.

    Writes a minimal PRD artifact so the DEFINE -> PRD_APPROVAL gate has
    something concrete to approve.
    """

    def __call__(
        self, header: StateHeader, fetch_detail: Callable[[], dict[str, Any]], workspace: Path
    ) -> AgentResult:
        prd_dir = workspace / "wiki" / "projects" / header.project_id
        prd_dir.mkdir(parents=True, exist_ok=True)
        prd_path = prd_dir / "PRD.md"
        _tmp = prd_path.with_suffix(".tmp")
        _tmp.write_text(
            f"# PRD — {header.project_id}\n\n"
            f"Tier: {header.tier}  Mode: {header.mode}  Size: {header.complexity}\n\n"
            "## Problem statement\nStub PRD generated by the control-plane demo.\n\n"
            "## Acceptance criteria\n1. The gate model halts and resumes correctly.\n"
        )
        _tmp.replace(prd_path)
        return AgentResult(
            ok=True,
            tokens=1200,
            detail_patch={"links": {"prd": str(prd_path.relative_to(workspace))}},
            summary="PRD drafted (stub)",
            artifacts=[str(prd_path.relative_to(workspace))],
        )


def stub_agent(name: str, tokens: int = 800) -> Agent:
    """Build a generic stub agent that succeeds and records ``tokens``."""

    def _run(
        header: StateHeader, fetch_detail: Callable[[], dict[str, Any]], workspace: Path
    ) -> AgentResult:
        return AgentResult(ok=True, tokens=tokens, summary=f"{name} completed (stub)")

    return _run


def default_registry() -> dict[str, Agent]:
    """Return a registry mapping every owner role to a stub implementation."""
    return {
        "PM": StubPM(),
        "Architect": stub_agent("Architect", 1500),
        "ReviewPanel": stub_agent("ReviewPanel", 3000),
        "Dev": stub_agent("Dev", 4000),
        "QA": stub_agent("QA", 2000),
        "CICD": stub_agent("CICD", 600),
        "Monitor": stub_agent("Monitor", 500),
    }


def live_registry() -> dict[str, Agent]:
    """Return a registry with the real PM agent wired in; all others remain stubs.

    Use this for interactive demos and live runs. Tests should use
    ``default_registry()`` with ``call_claude`` mocked to avoid network calls.
    """
    registry = default_registry()
    registry["PM"] = PMAgent()
    registry["Architect"] = ArchitectAgent()
    return registry
